version: "3.9"

services:
  analysis:
    build: .
    image: sudoku-analytics:latest
    container_name: sudoku_analytics
    volumes:
      - sudoku-data:/data      # Docker volume for dataset
      - ./output:/output       # local file for result
    restart: "no"
    command: python analysis.py

volumes:
  sudoku-data:
    external: true